[package]
name = "ethereum-programs"
version = "1.1.0"
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[build-dependencies]
glob = { workspace = true }
sphinx-helper = { workspace = true }

[features]
bench = []
