name: Test setup
inputs:
  pull_token:
    description: "Token to use for private repo access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up git private repo access
      shell: bash
      run: |
        git config --global url."https://${{ inputs.pull_token }}@github.com/".insteadOf ssh://git@github.com
        git config --global url."https://${{ inputs.pull_token }}@github.com".insteadOf https://github.com
    - name: Set env
      shell: bash
      run: |
        echo "RUSTFLAGS=${{env.RUSTFLAGS}} --cfg tokio_unstable -C opt-level=3" | tee -a $GITHUB_ENV
        echo "RUST_LOG=info" | tee -a $GITHUB_ENV
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: "**/go.sum"
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2024-05-31
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "aptos -> target"
    - uses: taiki-e/install-action@nextest
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update || true

        sudo apt-get install -y build-essential pkg-config libssl-dev libudev-dev cmake clang

        git clone https://github.com/lurk-lab/sphinx.git
        cd sphinx/cli
        cargo install --locked --force --path .

        cd ~
        cargo prove install-toolchain   
