apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "proof-server.fullname" . }}-hpa
  labels:
  {{- include "proof-server.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.hpa.minReplicas  }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.hpa.metrics.averageUtilization }}
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proof-server-deployment