[package]
name = "kadena-lc"
version = "1.0.0"
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
# LC crates
kadena-lc-core = { path = "../core" }
kadena-programs = { path = "../kadena-programs" }

# Sphinx crates
sphinx-sdk = { workspace = true }