[package]
name = "contracts-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate-contracts"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.86"
log = "0.4.21"
home = "0.5.9"
tempfile = "3.9.0"
sphinx-sdk = { workspace = true }
sphinx-prover = { workspace = true }