deployment:
  proofServer:
    env:
      containerPort: "8080"
      rustLog: debug
    image:
      repository: argumentcomputer/aptos-light-client
      tag: latest
    imagePullPolicy: IfNotPresent
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
