[workspace]
resolver = "2"

members = ["kadena-programs", "core"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/argumentcomputer/zk-light-clients"

[workspace.dependencies]
glob = "0.3.1"

# Sphinx dependencies
sphinx-derive = { git = "https://github.com/argumentcomputer/sphinx", tag = "v1.0.0" }
sphinx-sdk = { git = "https://github.com/argumentcomputer/sphinx", tag = "v1.0.0", features = ["plonk"] }
sphinx-zkvm = { git = "https://github.com/argumentcomputer/sphinx", tag = "v1.0.0" }
sphinx-helper = { git = "https://github.com/argumentcomputer/sphinx", tag = "v1.0.0" }
sphinx-prover = { git = "https://github.com/argumentcomputer/sphinx", tag = "v1.0.0" }
