apiVersion: v1
kind: ConfigMap
metadata:
  name: aptos-config
data:
  CONTAINER_PRIMARY_ADDR: "0.0.0.0"
  CONTAINER_PRIMARY_PORT: "6379"
  CONTAINER_SECONDARY_ADDR: "0.0.0.0"
  CONTAINER_SECONDARY_PORT: "6380"
  APTOS_NODE_URL: "127.0.0.1:8080"