[alias]
# Collection of project wide clippy lints. This is done via an alias because
# clippy doesn't currently allow for specifiying project-wide lints in a
# configuration file. This is a similar workaround to the ones presented here:
# <https://github.com/EmbarkStudios/rust-ecosystem/issues/59>
xclippy = [
    "clippy", "--workspace", "--all-targets", "--all-features", "--",
    "-Wclippy::all",
    "-Wclippy::cast_lossless",
    "-Wclippy::checked_conversions",
    "-Wclippy::dbg_macro",
    "-Wclippy::disallowed_methods",
    "-Wclippy::derive_partial_eq_without_eq",
    "-Wclippy::enum_glob_use",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::implicit_clone",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::macro_use_imports",
    "-Wclippy::manual_assert",
    "-Wclippy::manual_ok_or",
    "-Wclippy::map_flatten",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::missing_const_for_fn",
    "-Wclippy::needless_borrow",
    "-Wclippy::needless_continue",
    "-Wclippy::needless_for_each",
    "-Wclippy::needless_pass_by_value",
    "-Wclippy::option_option",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::single_match_else",
    "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::unnecessary_wraps",
    "-Wclippy::unnested_or_patterns",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    "-Wtrivial_numeric_casts",
    "-Wunused_lifetimes",
    "-Wunreachable_pub",
    "-Wtrivial_numeric_casts",
    "-Wunused_qualifications",
]

[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Show skipped tests in the CI output.
status-level = "skip"
# Do not cancel the test run on the first failure.
fail-fast = false
# Mark tests as slow after 5mins, kill them after 20mins
slow-timeout = { period = "300s", terminate-after = 4 }
# Retry failed tests once, marked flaky if test then passes
retries = 1
