[package]
name = "aptos-lc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# LC crates
aptos-lc-core = { path = "../core" }
aptos-programs = { path = "../aptos-programs" }

# Aptos crate
aptos-crypto = { workspace = true, optional = true }

# WP1 crates
wp1-sdk = { workspace = true }

#Others
serde = { workspace = true, features = ["derive", "rc"] }
thiserror = { workspace = true }

[dev-dependencies]
aptos-programs = { path = "../aptos-programs", features = ["bench"] }
bcs = { workspace = true }
cfg-if = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }

[features]
default = []
aptos = ["aptos-lc-core/aptos"]

[[bench]]
name = "merkle_base"
required-features = ["aptos"]
harness = false

[[bench]]
name = "bytes_base"
required-features = ["aptos"]
harness = false

[[bench]]
name = "sig_prod"
required-features = ["aptos"]
harness = false

[[bench]]
name = "ratchet_prod"
required-features = ["aptos"]
harness = false
