[package]
name = "aptos-lc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# LC crates
aptos-lc-core = { path = "../core" }
aptos-programs = { path = "../aptos-programs" }

# Aptos crate
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core/", tag = "aptos-node-v1.10.0", optional = true }

# WP1 crates
wp1-sdk = { git = "ssh://git@github.com/wormhole-foundation/wp1", branch = "dev" }

#Others
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "1.0.58"

[dev-dependencies]
aptos-programs = { path = "../aptos-programs", features = ["bench"] }
# From https://github.com/aptos-labs/aptos-core/blob/aptos-node-v1.10.0/Cargo.toml#L467
bcs = { git = "https://github.com/aptos-labs/bcs.git", rev = "d31fab9d81748e2594be5cd5cdf845786a30562d" }
cfg-if = "1.0.0"
criterion = { version = "0.5", features = ["html_reports"] }
pprof = { version = "0.13" }

[features]
default = []
aptos = ["aptos-lc-core/aptos"]
flamegraph = ["pprof/flamegraph", "pprof/criterion"]

[[bench]]
name = "merkle_base"
required-features = ["aptos"]
harness = false

[[bench]]
name = "bytes_base"
required-features = ["aptos"]
harness = false

[[bench]]
name = "sig_prod"
required-features = ["aptos"]
harness = false

[[bench]]
name = "ratchet_prod"
required-features = ["aptos"]
harness = false