[package]
name = "aptos-programs"
version = "1.0.0"
edition = "2021"
license-file = "../LICENSE.md"

[build-dependencies]
glob = { workspace = true }
sphinx-helper = { workspace = true }

[features]
bench = []
