[package]
version = "0.1.0"
name = "bytes-program"
edition = "2021"

[dependencies]
aptos-lc-core = { path = "../../core", package = "aptos-lc-core", default-features = false }
wp1-derive = { workspace = true }
wp1-zkvm = { workspace = true }
