[book]
authors = ["Thomas Chataigner"]
language = "en"
multilingual = false
src = "src"
title = "Kadena Light Client"
description = "A book about the Kadena ZK Light Client"

[preprocessor.external-links]

[output.html]
mathjax-support = true

[output.html.fold]
enable = true
level = 1