services:
  server-primary:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    command: sh -c "/app/proof_server --mode "single" --addr ${PRIMARY_ADDR}:${PRIMARY_PORT}
    environment:
      - RUST_LOG=debug
    restart: always
    depends_on:
      - server-secondary
    ports:
      - "${PRIMARY_PORT}:${PRIMARY_PORT}"