services:
  client:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        - LIGHT_CLIENT=ethereum
    command: sh -c "/app/client -p server-primary:${PRIMARY_PORT} -c ${CHECKPOINT_PROVIDER_ADDRESS} -b ${BEACON_NODE_ADDRESS} -r ${RPC_PROVIDER_ADDRESS}"
    environment:
      - RUST_LOG=debug
    restart: always
    depends_on:
      - server-primary
      - server-secondary