name: Benchmark pull requests
on:
  issue_comment:
    types: [ created ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: PR benchmark comment
    runs-on: ${{ matrix.runner_label }}
    strategy:
      matrix:
        include:
          - runner_label: buildjet-32vcpu-ubuntu-2204
            arch: x86
    if: |
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      contains(github.event.comment.body, '!benchmark')
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.PRIVATE_PULL_TOKEN }}@github.com".insteadOf https://github.com

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y pkg-config libudev-dev
          cargo install cargo-criterion

      - name: Run all benchmarks
        run: |
          for bench in $(find light-client/benches -name '*.rs'); do
            bench_name=$(basename $bench .rs)
            cargo criterion --features aptos --bench $bench_name > "${bench_name}_output.txt"
          done
        working-directory: ${{ github.workspace }}/aptos

      - name: Save benchmark output
        id: save_benchmark_output
        run: |
          for bench in $(find light-client/benches -name '*.rs'); do
            bench_name=$(basename $bench .rs)
            echo "::set-output name=${bench_name}_output::$(cat "${bench_name}_output.txt")"
          done
        working-directory: ${{ github.workspace }}/aptos

      - name: Comment on successful run
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            `!benchmark` action succeeded! :rocket:

            Benchmark output:
            ```
            ${{ steps.save_benchmark_output.outputs.*_output }}
            ```

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Comment on failing run
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            `!benchmark` action failed! :x:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}