name: Deploy mdBooks to GitHub Pages

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  # Detect changes in each subcrate
  changes:
    runs-on: ubuntu-latest
    outputs:
      # List of changed mdbooks
      books: ${{ steps.get-packages.outputs.packages }}
      aptos: ${{ steps.filter.outputs.aptos }}
      ethereum: ${{ steps.filter.outputs.ethereum }}
      kadena: ${{ steps.filter.outputs.kadena }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            aptos:
              - 'aptos/docs/**'
            ethereum:
              - 'ethereum/docs/**'
            kadena:
              - 'kadena/docs/**'
      - name: Get list of changed packages
        id: get-packages
        run: |
          BOOKS=$(echo '${{ steps.filter.outputs.changes }}' | jq -c '.')
          echo "books=$BOOKS" | tee -a "$GITHUB_OUTPUT"

  build:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.lc-packages != '[]' && needs.changes.outputs.packages != '' }}
    strategy:
      fail-fast: false
      matrix:
        # Parse JSON array containing names of all changed light client mdbooks,
        # e.g. ['aptos', 'ethereum', 'kadena'] if the `aptos`, `ethereum` and `kadena` mdbooks contain changes.
        light-client: ${{ fromJSON(needs.changes.outputs.books) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@mdbook
      - run: mdbook build
        working-directory: ${{ github.workspace }}/${{ matrix.light-client }}/docs
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ matrix.package }}/docs/book
          retention-days: 1

  deploy:
    if: ${{ (github.ref_name == 'dev' && github.event_name == 'push') && (needs.changes.outputs.books != '[]' && needs.changes.outputs.books != '') }}
    strategy:
      fail-fast: false
      matrix:
        # Parse JSON array containing names of all changed light client mdbooks,
        # e.g. ['aptos', 'ethereum', 'kadena'] if the `aptos`, `ethereum` and `kadena` mdbooks contain changes.
        light-client: ${{ fromJSON(needs.changes.outputs.books) }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/${{ matrix.light-client }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

