# Rebuilds proof fixtures for Solidity and Move (TBD) for smart contract verification tests
# The fixtures are located in `aptos/solidity/contracts/src/plonk_fixtures`
name: Update fixtures

on:
  push:
    branches:
      - "ci-fixtures"
  workflow_dispatch: {}
  # Once per day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fixtures:
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Generate Solidity `inclusion` fixtures
        run: |
          cargo run --release -- --program inclusion
        working-directory: ${{ github.workspace }}/aptos/solidity/fixture-generator
      - name: Generate Solidity `epoch_change` fixtures
        run: |
          cargo run --release -- --program epoch_change
        working-directory: ${{ github.workspace }}/aptos/solidity/fixture-generator
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v6
      #  with:
      #    branch: "ci-update-fixtures"
      #    title: "chore: Update fixtures"
      #    commit-message: "chore: Update fixtures"
      #    labels: "automated-issue"
