# Rebuilds proof fixtures for Solidity and Move (TBD) for smart contract verification tests
# The fixtures are located in `aptos/solidity/contracts/src/plonk_fixtures`
# Then opens a pull request with the changes
# Note: This workflow takes over 30 minutes due to parallel E2E proof generation for `inclusion` and `epoch_change`
name: Update fixtures

on:
  workflow_dispatch: {}
  # Once per day at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate-fixtures:
    runs-on: warp-ubuntu-latest-x64-32x
    strategy:
      matrix:
        fixture: [inclusion, epoch_change]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lurk-lab/ci-workflows
      - uses: ./.github/actions/ci-env
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./.github/actions/setup
        with:
          pull_token: ${{ secrets.REPO_TOKEN }}
      - name: Generate Solidity fixtures
        run: |
          cargo run --release -- --program ${{ matrix.fixture }} --language solidity
        working-directory: ${{ github.workspace }}/aptos/solidity/fixture-generator
      - name: Check for diff
        run: git diff
      - name: Upload fixture artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fixture }}_fixture
          path: ${{ github.workspace }}/aptos/solidity/contracts/src/plonk_fixtures/${{ matrix.fixture }}_fixture.json
          if-no-files-found: error
          overwrite: true
          retention-days: 1
      - name: Generate Move fixtures
          run: |
            cargo run --release -- --program ${{ matrix.fixture }} --language move
          working-directory: ${{ github.workspace }}/ethereum/move/sources/fixtures
        - name: Check for diff
          run: git diff
        - name: Upload fixture artifact
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.fixture }}_fixture
            path: ${{ github.workspace }}/ethereum/move/sources/fixtures/${{ matrix.fixture }}_fixture.json
            if-no-files-found: error
            overwrite: true
            retention-days: 1

  create-pull-request:
    needs: generate-fixtures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download inclusion fixture
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/aptos/solidity/contracts/src/plonk_fixtures/
          pattern: "*_fixture"
          merge-multiple: true
      - name: Download inclusion fixture
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/ethereum/move/sources/fixtures/
          pattern: "*_fixture"
          merge-multiple: true
      - name: Check for diff
        run: git diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "ci-update-fixtures"
          title: "chore: Update fixtures"
          commit-message: "chore: Update fixtures"
          labels: "automated-issue"
          reviewers: "tchataigner, storojs72, wwared, huitseeker, samuelburnham"
          body: |
            This is an automated PR updating the proof fixtures for Solidity and Move (TBD), which are used for smart contract verification tests.

            Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
