name: Tag release

on:
  pull_request:
    types: [ closed ]
    branches:
      - dev
      - release/*

jobs:
  # Creates a new tag if a release branch is merged
  tag-bump:
    if: |
      github.event.pull_request.merged == true &&
      ((startsWith(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.base.ref == 'dev') ||
      (startsWith(github.event.pull_request.head.ref, 'hotfix/') && startsWith(github.event.pull_request.base.ref, 'release/')))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | cut -d'/' -f 2)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          toTag: ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: ${{ steps.get-version.outputs.version }}
          target_commitish: ${{ startsWith(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.head.ref || github.event.pull_request.base.ref }}